# Generated by Django 6.1 on 2026-08-28 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('actor_uid', models.CharField(max_length=128)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('module_key', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('case_number', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('complainant', models.CharField(blank=True, max_length=255)),
                ('accused', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(default='Low', max_length=32)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=32)),
                ('assigned_officer', models.CharField(blank=True, max_length=255)),
                ('assigned_officer_uid', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('station_name', models.CharField(db_index=True, max_length=255)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case Record',
                'verbose_name_plural': 'Case Records',
                'db_table': 'cases_caserecord',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=32)),
                ('approved_by_super_admin_uid', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Admin User',
                'verbose_name_plural': 'Master Admin Users',
                'db_table': 'master_users',
            },
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('uid', models.CharField(help_text='Unique Officer Identifier', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('badge_number', models.CharField(blank=True, max_length=64)),
                ('designation', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('station_name', models.CharField(blank=True, max_length=255)),
                ('station_id', models.CharField(blank=True, max_length=64, null=True)),
                ('station_address', models.TextField(blank=True)),
                ('station_landline', models.CharField(blank=True, max_length=32)),
                ('govt_id', models.CharField(blank=True, max_length=64)),
                ('photo_url', models.URLField(blank=True, max_length=1024)),
                ('id_card_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('role_id', models.CharField(default='officer', max_length=64)),
                ('additional_stations', models.JSONField(blank=True, default=list)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected')], default='active', max_length=32)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('district_id', models.CharField(blank=True, max_length=64, null=True)),
                ('zone', models.CharField(blank=True, max_length=128, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('station_case_view_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Officer Profile',
                'verbose_name_plural': 'Officer Profiles',
                'db_table': 'users_officerprofile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateRegistry',
            fields=[
                ('state_code', models.CharField(help_text='e.g. MH, GJ, KA, DL', max_length=10, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100, unique=True)),
                ('schema_name', models.CharField(max_length=64, unique=True)),
                ('police_force_title', models.CharField(blank=True, help_text='e.g. Gujarat State Police', max_length=255)),
                ('department_logo_url', models.TextField(blank=True, help_text='State Police Department PNG Logo URL or Base64 Image Data', null=True)),
                ('super_admin_name', models.CharField(blank=True, max_length=255)),
                ('super_admin_email', models.EmailField(blank=True, max_length=254)),
                ('super_admin_phone', models.CharField(blank=True, max_length=32)),
                ('super_admin_rank', models.CharField(blank=True, help_text='e.g. Director General of Police (DGP)', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State Registry',
                'verbose_name_plural': 'State Registries',
                'db_table': 'states',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('officer_uid', models.CharField(max_length=128)),
                ('officer_name', models.CharField(max_length=255)),
                ('current_station', models.CharField(max_length=255)),
                ('requested_station', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('processed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transfer Request',
                'verbose_name_plural': 'Transfer Requests',
                'db_table': 'transfer_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('station_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255, unique=True)),
                ('district_name', models.CharField(blank=True, max_length=128)),
                ('zone', models.CharField(blank=True, max_length=128)),
                ('address', models.TextField(blank=True)),
                ('landline', models.CharField(blank=True, max_length=32)),
                ('pi_in_charge', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='admin_core.district')),
            ],
            options={
                'verbose_name': 'Police Station',
                'verbose_name_plural': 'Police Stations',
                'db_table': 'stations_policestation',
                'ordering': ['station_name'],
            },
        ),
    ]
