// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOoJp0rCmKDMpMjV0nE-bMxGMJ_7z8BgM',
    appId: '1:1037792018757:web:9fb4fe93dc03ceb6d3fe2c',
    messagingSenderId: '1037792018757',
    projectId: 'khakhi-diary',
    authDomain: 'khakhi-diary.firebaseapp.com',
    databaseURL: 'https://khakhi-diary-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khakhi-diary.firebasestorage.app',
    measurementId: 'G-C5RCYEWGD4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOoJp0rCmKDMpMjV0nE-bMxGMJ_7z8BgM',
    appId: '1:1037792018757:web:2a68d628feffb9c4d3fe2c',
    messagingSenderId: '1037792018757',
    projectId: 'khakhi-diary',
    authDomain: 'khakhi-diary.firebaseapp.com',
    databaseURL: 'https://khakhi-diary-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khakhi-diary.firebasestorage.app',
    measurementId: 'G-GEFWCRCLVD',
  );
}
